package com.wakka.dirgebridge;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import com.wakka.dirge.core.SaveVault;import java.io.*;import java.text.*;import java.util.*;

/** Player-facing Gothic launcher with Wakkan bridgekeeper styling. */
public final class MainActivity extends Activity {
 static final int IMPORT=10,REPORT=11,SAVE_EXPORT=12,SAVE_RESTORE=13;
 Payload payload;TextView status;Button play;boolean busy;String pendingReport;boolean tools;
 final int BG=0xff080a10,PANEL=0xff111722,PANEL2=0xff171c28,INK=0xfff0edf0,MUTED=0xffa9afbd,CRIMSON=0xff7d2035,RED=0xffc04359,CYAN=0xff39e7e1,CYAN2=0xff0b8f91;
 public void onCreate(Bundle b){super.onCreate(b);try{payload=new Payload(this);}catch(Exception e){payload=null;}showHome();}
 protected void onResume(){super.onResume();if(status!=null)refresh();}
 public void onBackPressed(){if(tools){showHome();}else super.onBackPressed();}

 void showHome(){tools=false;FrameLayout frame=base();ScrollView sc=new ScrollView(this);frame.addView(sc,new FrameLayout.LayoutParams(-1,-1));LinearLayout root=column();sc.addView(root);
  LinearLayout signal=row();TextView sig=label("◆  WAKKAN // BRIDGEKEEPER",11,CYAN,true);sig.setLetterSpacing(.13f);signal.addView(sig,new LinearLayout.LayoutParams(0,-2,1));TextView ver=label("0.2.4",11,0xff7f8aa0,true);signal.addView(ver);root.addView(signal);
  View divider=new View(this);divider.setBackgroundColor(0x5539e7e1);root.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));
  ImageView sigil=new ImageView(this);int sigilId=getResources().getIdentifier("ic_bridge","drawable",getPackageName());if(sigilId!=0)sigil.setImageResource(sigilId);sigil.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(sigil,lp(-1,dp(92),16,0));
  TextView title=label("DIRGE OF CERBERUS",34,INK,true);title.setTypeface(Typeface.create("serif",Typeface.BOLD));title.setLetterSpacing(.055f);title.setGravity(Gravity.CENTER);title.setPadding(0,dp(28),0,0);root.addView(title);
  TextView lost=label("L O S T   E P I S O D E",16,RED,true);lost.setGravity(Gravity.CENTER);lost.setLetterSpacing(.18f);root.addView(lost);
  TextView bridge=label("ANDROID BRIDGE // WAKKAN RESTORATION HOST",10,CYAN,false);bridge.setGravity(Gravity.CENTER);bridge.setLetterSpacing(.10f);bridge.setPadding(0,dp(5),0,dp(22));root.addView(bridge);
  root.addView(ornament());
  LinearLayout card=card();TextView eyebrow=label("RECOVERED SIGNAL",10,CYAN,true);eyebrow.setLetterSpacing(.15f);card.addView(eyebrow);status=label("Checking imported game data…",16,INK,true);status.setPadding(0,dp(6),0,dp(2));card.addView(status);TextView sub=label("English translation · original Japanese voice track · offline runtime",12,MUTED,false);card.addView(sub);root.addView(card,lp(-1,-2,0,12));
  play=bigButton("ENTER LOST EPISODE",true);play.setOnClickListener(v->{if(!busy&&payload!=null&&payload.installed(this))startActivity(new Intent(this,GameActivity.class));});root.addView(play,lp(-1,dp(68),0,12));
  LinearLayout actions=row();Button vault=smallButton("CHECKPOINT VAULT",false);vault.setOnClickListener(v->showCheckpoints());actions.addView(vault,new LinearLayout.LayoutParams(0,dp(54),1));space(actions,8);Button toolsB=smallButton("TOOLS / DIAGNOSTICS",true);toolsB.setOnClickListener(v->showTools());actions.addView(toolsB,new LinearLayout.LayoutParams(0,dp(54),1));root.addView(actions,lp(-1,-2,0,18));
  TextView wak=label("◈  CYAN WAKKAN LINK STABLE  ◈",10,0xff53bfc0,true);wak.setGravity(Gravity.CENTER);wak.setLetterSpacing(.12f);root.addView(wak,lp(-1,-2,0,20));
  TextView footer=label("A personal compatibility bridge for the recovered 2006 mobile game. Game files are imported separately and remain offline.",11,0xff777f90,false);footer.setGravity(Gravity.CENTER);root.addView(footer,lp(-1,-2,0,12));
  setContentView(frame);refresh();}

 void showTools(){tools=true;FrameLayout frame=base();ScrollView sc=new ScrollView(this);frame.addView(sc,new FrameLayout.LayoutParams(-1,-1));LinearLayout root=column();sc.addView(root);
  Button back=smallButton("‹ RETURN TO DIRGE",true);back.setOnClickListener(v->showHome());root.addView(back,lp(-1,dp(48),0,12));
  TextView h=label("BRIDGEKEEPER TOOLS",27,INK,true);h.setTypeface(Typeface.create("serif",Typeface.BOLD));h.setLetterSpacing(.06f);root.addView(h);TextView deck=label("Diagnostics, imported data, checkpoint vault and credits live here so the main launcher can stay gloriously dramatic.",13,MUTED,false);root.addView(deck,lp(-1,-2,0,14));
  root.addView(section("GAME DATA"));status=label("Checking…",14,INK,true);root.addView(status);Button imp=smallButton("Import / replace English game data ZIP",false);imp.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);});root.addView(imp,lp(-1,dp(52),0,8));
  TextView note=label("Existing English v0.1.1 game data does not need reimporting. Game-file imports preserve the game's scratchpad checkpoint files.",12,MUTED,false);root.addView(note,lp(-1,-2,0,12));
  root.addView(section("CHECKPOINT VAULT"));Button ck=smallButton("Open checkpoint backups",false);ck.setOnClickListener(v->showCheckpoints());root.addView(ck,lp(-1,dp(52),0,8));
  root.addView(section("DIAGNOSTICS"));Button rpt=smallButton("Save last runtime report",false);rpt.setOnClickListener(v->prepareReport());root.addView(rpt,lp(-1,dp(52),0,8));TextView diag=label("Reports include device/runtime details, graphics counters, resource fallbacks, audio events, input context and the full rolling log.",12,MUTED,false);root.addView(diag,lp(-1,-2,0,12));
  root.addView(section("CURRENT BASELINE"));root.addView(label("• English 1.0 text patch\n• Japanese voice/audio playback\n• Host-synchronized cutscene pause/resume\n• Compact 4-way movement\n• Native horizontal right-thumb aim\n• Original checkpoint backup/restore\n• Completely offline runtime",13,INK,false));
  root.addView(section("TRANSLATION / ATTRIBUTION"));root.addView(label("Translation: TurquoiseHammer\nHacking: Yuvi\nPlaytesting: Yuvi, TurquoiseHammer, Odysseus\nSpecial thanks: Shinra Archaeology\n\nIndependent compatibility project. No game files are included in this APK. No affiliation with Square Enix or NTT DOCOMO.",12,MUTED,false));
  root.addView(section("WAKKAN BRIDGE"));TextView ww=label("The cyan layer is the bridgekeeper: quiet signal geometry wrapped around the game's red-black Gothic identity. Runtime first. Pageantry second. Both intact.",12,0xff82d7d6,false);root.addView(ww,lp(-1,-2,0,24));
  setContentView(frame);refresh();}

 FrameLayout base(){FrameLayout f=new FrameLayout(this);Ui.insets(f);f.setBackgroundColor(BG);f.addView(new Backdrop(this),new FrameLayout.LayoutParams(-1,-1));return f;}
 LinearLayout column(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(20),dp(16),dp(20),dp(28));return r;}
 LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(PANEL,0xff30394b,16));return c;}
 TextView label(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));t.setLineSpacing(0,1.08f);return t;}
 TextView section(String s){TextView t=label(s,11,RED,true);t.setLetterSpacing(.15f);t.setPadding(0,dp(16),0,dp(7));return t;}
 Button bigButton(String s,boolean red){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(17);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(INK);b.setLetterSpacing(.06f);b.setBackground(round(red?CRIMSON:PANEL2,red?0xffa63b55:0xff44536a,16));return b;}
 Button smallButton(String s,boolean cyan){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(12);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(cyan?0xffbff9f5:INK);b.setBackground(round(cyan?0xff10262b:PANEL2,cyan?CYAN2:0xff3b4659,14));return b;}
 Drawable round(int fill,int stroke,int rad){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(rad));g.setStroke(dp(1),stroke);return g;}
 View ornament(){LinearLayout l=row();View a=new View(this),b=new View(this),c=new View(this);a.setBackgroundColor(0x557d2035);b.setBackgroundColor(CYAN);c.setBackgroundColor(0x557d2035);l.addView(a,new LinearLayout.LayoutParams(0,dp(1),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(7),dp(7));cp.setMargins(dp(10),0,dp(10),0);l.addView(c,cp);c.setRotation(45);l.addView(b,new LinearLayout.LayoutParams(0,dp(1),1));l.setPadding(0,0,0,dp(18));return l;}
 LinearLayout.LayoutParams lp(int w,int h,int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(0,dp(top),0,dp(bottom));return p;}
 void space(LinearLayout r,int n){Space s=new Space(this);r.addView(s,new LinearLayout.LayoutParams(dp(n),1));}
 int dp(int n){return Ui.dp(this,n);}

 void refresh(){if(status==null)return;boolean ok=payload!=null&&payload.installed(this);if(ok)status.setText("ENGLISH GAME DATA VERIFIED · READY");else if(payload==null)status.setText("BRIDGE MANIFEST ERROR");else status.setText("GAME DATA NOT INSTALLED · OPEN TOOLS TO IMPORT");if(play!=null)play.setEnabled(ok&&!busy);}
 void prepareReport(){pendingReport=Ui.device()+"\nSAVED SESSION\n"+Ui.read(new File(getFilesDir(),"latest-report.txt"))+"\nFULL LOG\n"+Ui.read(new File(getFilesDir(),"runtime.log"))+"\nIMPORT\n"+Ui.read(new File(getFilesDir(),"import-status.txt"));createPicker(REPORT,"text/plain","Dirge-Bridge-0.2.4-report.txt");}
 void createPicker(int request,String type,String name){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(type).putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,request);}
 void openPicker(int request){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/zip");startActivityForResult(i,request);}
 void showCheckpoints(){SaveVault v=new SaveVault(getFilesDir());String summary;try{summary=v.summary();}catch(Exception e){summary="Checkpoint status unavailable: "+e.getMessage();}new AlertDialog.Builder(this).setTitle("Checkpoint Vault").setMessage(summary+"\n\nThese are the game's own checkpoints, not exact save states.").setItems(new String[]{"Export checkpoint ZIP","Restore exported ZIP","Restore latest automatic backup","About checkpoints"},(d,w)->{if(w==0){String stamp=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date());createPicker(SAVE_EXPORT,"application/zip","Dirge-Checkpoint-"+stamp+".zip");}else if(w==1)openPicker(SAVE_RESTORE);else if(w==2)confirmRestore(null);else new AlertDialog.Builder(this).setTitle("About checkpoints").setMessage("Before launches, existing scratchpad checkpoint files are backed up. Continue may restart a room or encounter rather than returning to an exact paused moment. Keep the game closed while exporting or restoring.").setPositiveButton("Close",null).show();}).setNegativeButton("Close",null).show();}
 void confirmRestore(Uri uri){new AlertDialog.Builder(this).setTitle("Replace current checkpoint files?").setMessage("Your current checkpoint files are backed up first. Nothing changes if validation fails. The game must be closed.").setPositiveButton("Restore",(d,w)->work(()->{SaveVault v=new SaveVault(getFilesDir());if(uri==null)v.restoreLastBackup();else try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Cannot read checkpoint ZIP");v.restore(in);}return "Checkpoint files restored. Open the game and choose Continue.";})).setNegativeButton("Cancel",null).show();}
 interface Job{String run()throws Exception;}
 void work(Job j){if(busy)return;busy=true;refresh();new Thread(()->{String m;boolean fail=false;try{m=j.run();}catch(Exception e){m="Operation failed: "+e.getMessage();fail=true;}final String mm=m;final boolean ff=fail;runOnUiThread(()->{busy=false;refresh();if(ff)Ui.error(this,mm);else Toast.makeText(this,mm,Toast.LENGTH_LONG).show();});},"BridgekeeperStorage").start();}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();
  if(request==REPORT){try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new IOException("Cannot write report");out.write(pendingReport.getBytes("UTF-8"));Toast.makeText(this,"Report saved.",Toast.LENGTH_LONG).show();}catch(Exception e){Ui.error(this,"Report save failed: "+e.getMessage());}return;}
  if(request==SAVE_EXPORT){work(()->{try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new IOException("Cannot create checkpoint ZIP");new SaveVault(getFilesDir()).exportTo(out);}return "Checkpoint ZIP exported.";});return;}
  if(request==SAVE_RESTORE){confirmRestore(uri);return;}
  if(request==IMPORT){busy=true;refresh();if(status!=null)status.setText("VERIFYING 19 IMPORTED FILES…");new Thread(()->{String m;boolean fail=false;try{payload.importZip(this,uri);m="English game data verified. Existing checkpoints preserved.";}catch(Exception e){m="Import failed: "+e;fail=true;}try{Ui.write(new File(getFilesDir(),"import-status.txt"),m);}catch(Exception ignored){}final String mm=m;final boolean ff=fail;runOnUiThread(()->{busy=false;refresh();if(ff)Ui.error(this,mm);else Toast.makeText(this,mm,Toast.LENGTH_LONG).show();});},"DirgeImporter").start();}
 }
 static final class Backdrop extends View {final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);Backdrop(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();c.drawColor(0xff080a10);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0x257d2035);for(int y=70;y<h;y+=118)c.drawLine(0,y,w,y+44,p);p.setColor(0x2239e7e1);p.setStrokeWidth(1);c.drawLine(w*.08f,0,w*.08f,h,p);c.drawLine(w*.92f,0,w*.92f,h,p);p.setStyle(Paint.Style.FILL);p.setColor(0x1839e7e1);for(int y=115;y<h;y+=220){c.save();c.rotate(45,w*.08f,y);c.drawRect(w*.08f-6,y-6,w*.08f+6,y+6,p);c.restore();}p.setColor(0x197d2035);c.drawCircle(w*.5f,h*.22f,w*.34f,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(0x3044d8d5);c.drawCircle(w*.5f,h*.22f,w*.35f,p);}}
}
